package me.phoenixra.atumvr.core.enums;

import lombok.Getter;
import org.lwjgl.openxr.XR10;

import java.util.HashMap;

public enum XRActionResult {
    SUCCESS(XR10.XR_SUCCESS),
    TIMEOUT_EXPIRED(XR10.XR_TIMEOUT_EXPIRED),
    SESSION_LOSS_PENDING(XR10.XR_SESSION_LOSS_PENDING),
    EVENT_UNAVAILABLE(XR10.XR_EVENT_UNAVAILABLE),
    SPACE_BOUNDS_UNAVAILABLE(XR10.XR_SPACE_BOUNDS_UNAVAILABLE),
    SESSION_NOT_FOCUSED(XR10.XR_SESSION_NOT_FOCUSED),
    ERROR_VALIDATION_FAILURE(XR10.XR_ERROR_VALIDATION_FAILURE),
    ERROR_RUNTIME_FAILURE(XR10.XR_ERROR_RUNTIME_FAILURE),
    ERROR_OUT_OF_MEMORY(XR10.XR_ERROR_OUT_OF_MEMORY),
    ERROR_API_VERSION_UNSUPPORTED(XR10.XR_ERROR_API_VERSION_UNSUPPORTED),
    ERROR_INITIALIZATION_FAILED(XR10.XR_ERROR_INITIALIZATION_FAILED),
    ERROR_FUNCTION_UNSUPPORTED(XR10.XR_ERROR_FUNCTION_UNSUPPORTED),
    ERROR_FEATURE_UNSUPPORTED(XR10.XR_ERROR_FEATURE_UNSUPPORTED),
    ERROR_EXTENSION_NOT_PRESENT(XR10.XR_ERROR_EXTENSION_NOT_PRESENT),
    ERROR_LIMIT_REACHED(XR10.XR_ERROR_LIMIT_REACHED),
    ERROR_SIZE_INSUFFICIENT(XR10.XR_ERROR_SIZE_INSUFFICIENT),
    ERROR_HANDLE_INVALID(XR10.XR_ERROR_HANDLE_INVALID),
    ERROR_INSTANCE_LOST(XR10.XR_ERROR_INSTANCE_LOST),
    ERROR_SESSION_RUNNING(XR10.XR_ERROR_SESSION_RUNNING),
    ERROR_SESSION_NOT_RUNNING(XR10.XR_ERROR_SESSION_NOT_RUNNING),
    ERROR_SESSION_LOST(XR10.XR_ERROR_SESSION_LOST),
    ERROR_SYSTEM_INVALID(XR10.XR_ERROR_SYSTEM_INVALID),
    ERROR_PATH_INVALID(XR10.XR_ERROR_PATH_INVALID),
    ERROR_PATH_COUNT_EXCEEDED(XR10.XR_ERROR_PATH_COUNT_EXCEEDED),
    ERROR_PATH_FORMAT_INVALID(XR10.XR_ERROR_PATH_FORMAT_INVALID),
    ERROR_PATH_UNSUPPORTED(XR10.XR_ERROR_PATH_UNSUPPORTED),
    ERROR_LAYER_INVALID(XR10.XR_ERROR_LAYER_INVALID),
    ERROR_LAYER_LIMIT_EXCEEDED(XR10.XR_ERROR_LAYER_LIMIT_EXCEEDED),
    ERROR_SWAPCHAIN_RECT_INVALID(XR10.XR_ERROR_SWAPCHAIN_RECT_INVALID),
    ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED(XR10.XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED),
    ERROR_ACTION_TYPE_MISMATCH(XR10.XR_ERROR_ACTION_TYPE_MISMATCH),
    ERROR_SESSION_NOT_READY(XR10.XR_ERROR_SESSION_NOT_READY),
    ERROR_SESSION_NOT_STOPPING(XR10.XR_ERROR_SESSION_NOT_STOPPING),
    ERROR_TIME_INVALID(XR10.XR_ERROR_TIME_INVALID),
    ERROR_REFERENCE_SPACE_UNSUPPORTED(XR10.XR_ERROR_REFERENCE_SPACE_UNSUPPORTED),
    ERROR_FILE_ACCESS_ERROR(XR10.XR_ERROR_FILE_ACCESS_ERROR),
    ERROR_FILE_CONTENTS_INVALID(XR10.XR_ERROR_FILE_CONTENTS_INVALID),
    ERROR_FORM_FACTOR_UNSUPPORTED(XR10.XR_ERROR_FORM_FACTOR_UNSUPPORTED),
    ERROR_FORM_FACTOR_UNAVAILABLE(XR10.XR_ERROR_FORM_FACTOR_UNAVAILABLE),
    ERROR_API_LAYER_NOT_PRESENT(XR10.XR_ERROR_API_LAYER_NOT_PRESENT),
    ERROR_CALL_ORDER_INVALID(XR10.XR_ERROR_CALL_ORDER_INVALID),
    ERROR_GRAPHICS_DEVICE_INVALID(XR10.XR_ERROR_GRAPHICS_DEVICE_INVALID),
    ERROR_POSE_INVALID(XR10.XR_ERROR_POSE_INVALID),
    ERROR_INDEX_OUT_OF_RANGE(XR10.XR_ERROR_INDEX_OUT_OF_RANGE),
    ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED(XR10.XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED),
    ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED(XR10.XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED),
    ERROR_NAME_DUPLICATED(XR10.XR_ERROR_NAME_DUPLICATED),
    ERROR_NAME_INVALID(XR10.XR_ERROR_NAME_INVALID),
    ERROR_ACTIONSET_NOT_ATTACHED(XR10.XR_ERROR_ACTIONSET_NOT_ATTACHED),
    ERROR_ACTIONSETS_ALREADY_ATTACHED(XR10.XR_ERROR_ACTIONSETS_ALREADY_ATTACHED),
    ERROR_LOCALIZED_NAME_DUPLICATED(XR10.XR_ERROR_LOCALIZED_NAME_DUPLICATED),
    ERROR_LOCALIZED_NAME_INVALID(XR10.XR_ERROR_LOCALIZED_NAME_INVALID),
    ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING(XR10.XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING),
    ERROR_RUNTIME_UNAVAILABLE(XR10.XR_ERROR_RUNTIME_UNAVAILABLE);


    @Getter
    private final int id;

    private static final HashMap<Integer, XRActionResult> values = new HashMap<>();


    XRActionResult(int id){
        this.id = id;
    }

    public static XRActionResult fromId(int id){
        if(values.isEmpty()){
            for(XRActionResult event : values()){
                values.put(event.id,event);
            }
        }
        return values.get(id);
    }
}
