plugins {
    id 'maven-publish'
}

architectury {

    common(rootProject.enabled_platforms.split(","))
}

loom{
    accessWidenerPath = project(":visor-api").file("src/main/resources/visor.accesswidener")
}

dependencies {
    compileOnly(project(path: ':visor-api', configuration: 'namedElements'))

    // @Environment annotation and mixin extras
    modImplementation(libs.fabric.loader)

    modApi(libs.architectury.lib)

    api(libs.atumvr.api)
    api(libs.atumvr.core)

    //Other mods
    modCompileOnly(libs.mods.sodium)


}

publishing {
    publications {
        maven(MavenPublication) {
            // This automatically includes your API's compiled JAR file
            from components.java
        }
    }
}
