architectury {

    common(rootProject.enabled_platforms.split(","))
}
loom{
    accessWidenerPath = file("src/main/resources/visor.accesswidener")
}
dependencies {
    // @Environment annotation and mixin extras
    compileOnly(libs.fabric.loader)

    api(libs.atumvr.core)

    compileOnly(libs.bundles.annotations)
    annotationProcessor(libs.bundles.annotations)
}