architectury {

    common(rootProject.enabled_platforms.split(","))
}
loom{
    accessWidenerPath = file("src/main/resources/visor.accesswidener")
}
dependencies {
    // @Environment annotation and mixin extras
    compileOnly(libs.fabric.loader)

    // ---- LOCAL DEPENDENCY
    modApi name: 'atumvr-api-1.13.0beta-snapshot#0'
    modApi name: 'atumvr-core-1.13.0beta-snapshot#0'
    // ----
    //api(libs.atumvr.api)
    //api(libs.atumvr.core)
    api(libs.atumvr.config)

    compileOnly(libs.bundles.annotations)
    annotationProcessor(libs.bundles.annotations)
}