plugins {
    id 'maven-publish'
    alias(libs.plugins.shadow)
}

loom{
    accessWidenerPath = file("src/main/resources/visor.accesswidener")
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}
dependencies {
    // @Environment annotation and mixin extras
    compileOnly(libs.fabric.loader)

    api(libs.atumvr.api)
    api(libs.atumvr.core)


    shadowCommon(libs.atumvr.api) { transitive = false }
    shadowCommon(libs.atumvr.core) { transitive = false }
    shadowCommon(libs.atumvr.config)
}


shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"
    exclude "org.joml"
    exclude "org.lwjgl"
    exclude "org.slf4j"
    duplicatesStrategy DuplicatesStrategy.EXCLUDE
    configurations = [
            project.configurations.shadowCommon,
    ]
    archiveClassifier.set("")

    relocate("org.yaml","me.phoenixra.libs.org.yaml")
    relocate("org.tomlj","me.phoenixra.libs.org.tomlj")
    relocate("org.checkerframework","me.phoenixra.libs.org.checkerframework")
    relocate("org.antlr","me.phoenixra.libs.org.antlr")

    relocate("com.google.gson","me.phoenixra.libs.com.google.gson")
    relocate("redempt.crunch","me.phoenixra.libs.redempt.crunch")

    relocate("org.reflections","me.phoenixra.libs.org.reflections")



}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set('obf')
}



publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}